# Generated by Django 3.1.4 on 2020-12-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201211_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='manual/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='functions/', verbose_name='Изображение'),
        ),
    ]
