# Generated by Django 3.1.4 on 2020-12-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201211_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование требований')),
                ('CPU', models.CharField(max_length=50, verbose_name='CPU')),
                ('RAM', models.CharField(max_length=50, verbose_name='RAM')),
                ('HDD_SSD', models.CharField(max_length=50, verbose_name='HDD_SSD')),
                ('Video', models.CharField(max_length=50, verbose_name='Видеоадаптер')),
                ('NetworkCard', models.CharField(max_length=50, verbose_name='Сетевая карта')),
                ('Manipulators', models.CharField(blank=True, max_length=200, null=True, verbose_name='Манипуляторы')),
            ],
            options={
                'verbose_name': 'Системные аппаратные требования',
                'verbose_name_plural': 'Системные аппаратные требования',
            },
        ),
        migrations.CreateModel(
            name='System_Prog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование требований')),
                ('OS', models.CharField(max_length=50, verbose_name='OS')),
                ('DOP', models.CharField(max_length=50, verbose_name='Дополнительное ПО или СУБД')),
            ],
            options={
                'verbose_name': 'Системные программные требования',
                'verbose_name_plural': 'Системные программные требования',
            },
        ),
        migrations.AlterField(
            model_name='function',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='manual/', verbose_name='Изображение'),
        ),
    ]
