# Generated by Django 3.1.4 on 2020-12-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201212_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_app',
            name='Video',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Видеоадаптер'),
        ),
    ]
