# Generated by Django 3.1.4 on 2020-12-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201212_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, max_length=50, null=True, verbose_name='Дата добавления'),
        ),
    ]
