# Generated by Django 3.1.4 on 2020-12-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201212_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date',
            field=models.DateField(auto_now_add=True, max_length=50, null=True, verbose_name='Дата добавления'),
        ),
    ]
